#!/usr/bin/env nextflow

// Specify DSL2
nextflow.enable.dsl=2

/*
PREPARE INPUTS
*/

// Check mandatory parameters
if (!params.input) {
    exit 1, 'Input samplesheet not specified!'
} else {
    ch_input = Channel
            .fromPath( params.input )
            .splitCsv(header:true)
            .map { row -> [ row.sample, file(row.fastq, checkIfExists: true) ] }
}


// Check if genome exists in the config file
if (params.org  && !params.genomes.containsKey(params.org)) {
    exit 1, "The provided genome '${params.org}' is not available. Currently the available genomes are ${params.genomes.keySet().join(", ")}"
}

/*
PREPARE GENOME CHANNELS
*/

if(params.org) {

    params.fasta = params.genomes[ params.org ].fasta
    params.gtf = params.genomes[ params.org ].gtf
    params.star_index = params.genomes[ params.org ].star_index
    params.contaminants_fasta = params.genomes[ params.org ].contaminants_fasta
    params.transcript_info = params.genomes[ params.org ].transcript_info
    params.transcript_fasta = params.genomes[ params.org ].transcript_fasta

}  else {

    if(!params.fasta ) { exit 1, '--fasta is not specified.' }
    if(!params.gtf ) { exit 1, '--gtf is not specified.' }
    if(!params.contaminants_fasta && !params.skip_premap ) {exit 1, '--contaminants_fasta is not specified.' }

}


ch_genome_fasta = file(params.fasta, checkIfExists: true)
ch_contaminants_fasta = params.skip_premap ? Channel.empty() : file(params.contaminants_fasta, checkIfExists: true)
ch_genome_gtf = file(params.gtf, checkIfExists: true)

/*
MultiQC config
*/
ch_multiqc_config = Channel.fromPath(params.multiqc_config, checkIfExists: true)

/*
MultiQC sample highlighting by the optional, free-text `group` column.
Builds a MultiQC config that colours each sample by its samplesheet `group` value,
using a deterministic colourblind-conscious 12-colour palette (with an HSV-generated
palette as fallback when there are more than 12 groups). Fully backward compatible:
if there is no `group` column (or all its values are empty) an inert config is written
and no highlighting is applied.
*/

ch_multiqc_group_config = Channel
            .fromPath( params.input )
            .splitCsv( header: true )
            .map { row -> [ row.sample?.toString()?.trim(), row.group?.toString()?.trim() ] }
            .filter { it[0] && it[1] }
            .toList()
            .map { pairs -> build_group_highlight_config( pairs ) }
            .collectFile( name: 'multiqc_group_config.yaml' )

/*
Channel for OPTIONAL INPUT - contains a tuple with sample ids as keys, but no path/file
*/

ch_optional = Channel
            .fromPath( params.input )
            .splitCsv(header:true)
            .map { row -> [ row.sample, [] ] }


/*
SUBWORKFLOWS
*/

include { PREPARE_RIBOSEQ_REFERENCE } from './subworkflows/prepare_reference.nf'
include { PREPROCESS_READS } from './subworkflows/preprocess_reads.nf'
include { DEDUPLICATE } from './subworkflows/dedup.nf'
include { MAPPING_LENGTH_ANALYSES } from './subworkflows/mapping_length_analyses.nf'
include { GET_GENE_LEVEL_COUNTS } from './subworkflows/gene_level_counts.nf'
include { RUN_RIBOCUTTER } from './subworkflows/ribocutter_analysis.nf'

/*
MODULES
*/

include { FASTQC } from './modules/nf-core/fastqc/main'
include { PREMAP } from './modules/local/premap.nf'
include { MAP } from './modules/local/map.nf'
include { RIBOSEQ_QC } from './modules/local/riboseq_qc.nf'
include { SUMMARISE_RIBOSEQ_QC } from './modules/local/riboseq_qc.nf'
include { TRACK_READS } from './modules/local/riboseq_qc.nf'
include { IDENTIFY_PSITES } from './modules/local/ribowaltz.nf'
include { RUST_QC } from './modules/local/ribowaltz.nf'
include { GET_COVERAGE_TRACKS } from './modules/local/get_tracks.nf'
include { GET_PSITE_TRACKS } from './modules/local/ribowaltz.nf'
include { PCA } from './modules/local/riboseq_qc.nf'
include { MULTIQC } from './modules/local/multiqc.nf'


/*
FUNCTIONS - MultiQC sample highlighting by samplesheet `group`
*/

// Colourblind-conscious qualitative palette (Paul Tol 'bright' + 'light'); covers up to 12 groups.
def group_highlight_palette() {
    return [
        '#4477AA', '#EE6677', '#228833', '#CCBB44', '#66CCEE', '#AA3377',
        '#BBBBBB', '#77AADD', '#EE8866', '#EEDD88', '#FFAABB', '#99DDFF'
    ]
}

// Evenly-spaced HSV colour as #RRGGBB; fallback when there are more groups than palette colours.
def hsv_to_hex(h, s, v) {
    def c = java.awt.Color.getHSBColor(h as float, s as float, v as float)
    return String.format('#%02X%02X%02X', c.red, c.green, c.blue)
}

// Escape a sample id so MultiQC's (Python) regex engine matches it literally.
def escape_py_regex(s) {
    return s.toString().replaceAll('[\\\\^$.|?*+()\\[\\]{}]') { m -> '\\' + m }
}

// Build the MultiQC highlight config (YAML text) from a list of [sample, group] pairs.
def build_group_highlight_config(pairs) {

    def palette = group_highlight_palette()
    def header  = '# Auto-generated by riboseq-flow: highlight MultiQC samples by the samplesheet `group` column.\n'

    if (!pairs) {
        return header + '# No `group` column found (or all values empty); no sample highlighting applied.\n'
    }

    // Deterministic colour per group, ordered by sorted group name.
    def groups = pairs.collect { it[1] }.unique().sort()
    def group_colour = [:]
    groups.eachWithIndex { grp, i ->
        group_colour[grp] = (groups.size() <= palette.size()) ?
            palette[i] :
            hsv_to_hex((i as double) / groups.size(), 0.65d, 0.85d)
    }

    // One anchored, regex-escaped pattern per sample, paired with its group colour.
    def pattern_lines = []
    def colour_lines  = []
    pairs.each { p ->
        def pat = '^' + escape_py_regex(p[0]) + '$'
        pattern_lines << "  - '" + pat.replace("'", "''") + "'"
        colour_lines  << "  - '" + group_colour[p[1]] + "'"
    }

    def out = new StringBuilder()
    out << header
    out << '# group -> colour: ' << groups.collect { "${it} = ${group_colour[it]}" }.join(', ') << '\n'
    out << 'highlight_regex: true\n'
    out << 'highlight_patterns:\n'
    out << pattern_lines.join('\n') << '\n'
    out << 'highlight_colors:\n'
    out << colour_lines.join('\n') << '\n'
    return out.toString()
}


/*
MAIN WORKFLOW
*/

workflow RIBOSEQ {

    // Prepare annotation
    PREPARE_RIBOSEQ_REFERENCE(
        ch_genome_fasta,
        ch_genome_gtf,
        ch_contaminants_fasta
    )

    // Extract UMIs and/or trim adapters and filter on min length, then run FASTQC
    PREPROCESS_READS(ch_input)
    FASTQC(PREPROCESS_READS.out.fastq)

    // Run ribocutter on trimmed reads only (adapter-trimmed, but not 5' G / poly-A cut or length filtered)
    if (!params.skip_ribocutter) {
        RUN_RIBOCUTTER(
            PREPROCESS_READS.out.trimmed_fastq
            )
    }

    // Align reads
    if (!params.skip_premap) {

        // Premap to the contaminant RNA genome
        PREMAP(
            PREPROCESS_READS.out.fastq,
            PREPARE_RIBOSEQ_REFERENCE.out.contaminants_bowtie2_index.collect()
        )

        MAP(
            PREMAP.out.unmapped,
            PREPARE_RIBOSEQ_REFERENCE.out.genome_star_index.collect()
        )

    } else {

        MAP(
            PREPROCESS_READS.out.fastq,
            PREPARE_RIBOSEQ_REFERENCE.out.genome_star_index.collect()
        )
    }

    if (params.with_umi) {

        // Remove duplicate reads from BAM file based on UMIs
        DEDUPLICATE(
            MAP.out.genome_bam,
            MAP.out.transcriptome_bam
        )
    }


    // riboseq QC
    if (!params.skip_qc) {
        // Mapping length analysis, visualisation and read fate tracking

        if (!params.skip_premap && params.with_umi) {

            MAPPING_LENGTH_ANALYSES(
                MAP.out.genome_bam,
                PREPROCESS_READS.out.cut_fastq,
                DEDUPLICATE.out.dedup_genome_bam,
                PREMAP.out.unmapped
            )

            RIBOSEQ_QC(
                DEDUPLICATE.out.dedup_transcriptome_bam
                    .join(MAPPING_LENGTH_ANALYSES.out.before_dedup_length_analysis)
                    .join(MAPPING_LENGTH_ANALYSES.out.after_premap_length_analysis)
                    .join(MAPPING_LENGTH_ANALYSES.out.after_dedup_length_analysis),
                PREPARE_RIBOSEQ_REFERENCE.out.transcript_info.collect()
            )

            // Track read fate through pipeline
            TRACK_READS(
                PREPROCESS_READS.out.logs
                    .join(PREMAP.out.log)
                    .join(MAP.out.log)
                    .join(DEDUPLICATE.out.dedup_genome_log)
                    .join(RIBOSEQ_QC.out.qc)
            )

        } else if (params.skip_premap && params.with_umi) {

            MAPPING_LENGTH_ANALYSES(
                MAP.out.genome_bam,
                PREPROCESS_READS.out.cut_fastq,
                DEDUPLICATE.out.dedup_genome_bam,
                Channel.empty()
            )

            RIBOSEQ_QC(
                DEDUPLICATE.out.dedup_transcriptome_bam
                    .join(MAPPING_LENGTH_ANALYSES.out.before_dedup_length_analysis)
                    .join(MAPPING_LENGTH_ANALYSES.out.after_premap_length_analysis)
                    .join(MAPPING_LENGTH_ANALYSES.out.after_dedup_length_analysis),
                PREPARE_RIBOSEQ_REFERENCE.out.transcript_info.collect()
            )

            TRACK_READS(
                PREPROCESS_READS.out.logs
                    .join(MAP.out.log)
                    .join(DEDUPLICATE.out.dedup_genome_log)
                    .join(RIBOSEQ_QC.out.qc)
                    .join(ch_optional)
            )


        } else if (!params.skip_premap && !params.with_umi) {

            MAPPING_LENGTH_ANALYSES(
                MAP.out.genome_bam,
                PREPROCESS_READS.out.cut_fastq,
                Channel.empty(),
                PREMAP.out.unmapped
            )

            RIBOSEQ_QC(
                MAP.out.transcriptome_bam
                    .join(MAPPING_LENGTH_ANALYSES.out.before_dedup_length_analysis)
                    .join(MAPPING_LENGTH_ANALYSES.out.after_premap_length_analysis)
                    .join(MAPPING_LENGTH_ANALYSES.out.after_dedup_length_analysis),
                PREPARE_RIBOSEQ_REFERENCE.out.transcript_info.collect()
            )

            TRACK_READS(
                PREPROCESS_READS.out.logs
                    .join(PREMAP.out.log)
                    .join(MAP.out.log)
                    .join(RIBOSEQ_QC.out.qc)
                    .join(ch_optional)
            )

        } else if (params.skip_premap && !params.with_umi) {

            MAPPING_LENGTH_ANALYSES(
                MAP.out.genome_bam,
                PREPROCESS_READS.out.cut_fastq,
                Channel.empty(),
                Channel.empty()
            )

            RIBOSEQ_QC(
                MAP.out.transcriptome_bam
                    .join(MAPPING_LENGTH_ANALYSES.out.before_dedup_length_analysis)
                    .join(MAPPING_LENGTH_ANALYSES.out.after_premap_length_analysis)
                    .join(MAPPING_LENGTH_ANALYSES.out.after_dedup_length_analysis),
                PREPARE_RIBOSEQ_REFERENCE.out.transcript_info.collect()
            )

            TRACK_READS(
                PREPROCESS_READS.out.logs
                    .join(MAP.out.log)
                    .join(RIBOSEQ_QC.out.qc)
                    .join(ch_optional)
                    .join(ch_optional)
            )

        }

        ch_merge_qc = RIBOSEQ_QC.out.qc
            .map { [ it[1] ] }
            .collect()

        ch_merge_read_length = RIBOSEQ_QC.out.fq_length_distr
            .map { [ it[1] ] }
            .collect()

        ch_merge_useful_length = RIBOSEQ_QC.out.useful_length_distr
            .map { [ it[1] ] }
            .collect()

        ch_merge_region_counts = RIBOSEQ_QC.out.region_counts
            .map { [ it[1] ] }
            .collect()

        ch_merge_start_dist = RIBOSEQ_QC.out.start_dist
            .map { [ it[1] ] }
            .collect()

        ch_merge_frame = RIBOSEQ_QC.out.frame_counts
            .map { [ it[1] ] }
            .collect()

        ch_merge_mapping_counts = TRACK_READS.out.mapping_counts
            .map { [ it[1] ] }
            .collect() 

        ch_merge_legth_filter = TRACK_READS.out.length_filter
            .map { [ it[1] ] }
            .collect() 

        SUMMARISE_RIBOSEQ_QC(
            ch_merge_qc,
            ch_merge_read_length,
            ch_merge_useful_length,
            ch_merge_region_counts,
            ch_merge_start_dist,
            ch_merge_mapping_counts,
            ch_merge_frame,
            ch_merge_legth_filter
        )

    }

    // Get gene-level counts from BAM alignments using featureCounts and coverage tracks using deepTools
    if (params.with_umi) {
        GET_GENE_LEVEL_COUNTS(
            DEDUPLICATE.out.dedup_genome_bam,
            PREPARE_RIBOSEQ_REFERENCE.out.genome_gtf.map{ it[1] }
        )

        GET_COVERAGE_TRACKS(DEDUPLICATE.out.dedup_genome_bam)

    } else {
        GET_GENE_LEVEL_COUNTS(
            MAP.out.genome_bam,
            PREPARE_RIBOSEQ_REFERENCE.out.genome_gtf.map{ it[1] }
        )

        GET_COVERAGE_TRACKS(MAP.out.genome_bam)

    }

    // Get P sites
    if (!params.skip_psite) {

         if (params.with_umi) {

            IDENTIFY_PSITES(
                DEDUPLICATE.out.dedup_transcriptome_bam
                    .map { [it[1]] }
                    .collect(),
                PREPARE_RIBOSEQ_REFERENCE.out.genome_gtf
                    .map { it[1] },
                PREPARE_RIBOSEQ_REFERENCE.out.genome_fasta
                    .map { it[1] },
                PREPARE_RIBOSEQ_REFERENCE.out.transcript_info
            )


        } else {

            IDENTIFY_PSITES(
                MAP.out.transcriptome_bam
                    .map { [it[1]] }
                    .collect(),
                PREPARE_RIBOSEQ_REFERENCE.out.genome_gtf
                    .map { it[1] },
                PREPARE_RIBOSEQ_REFERENCE.out.genome_fasta
                    .map { it[1] },
                PREPARE_RIBOSEQ_REFERENCE.out.transcript_info
            )


        }

        // Convert codon coverage from transcriptomic to genomic coordinates
        if (params.genomic_codon_coverage) {
        GET_PSITE_TRACKS(
            IDENTIFY_PSITES.out.psites.flatten(),
            PREPARE_RIBOSEQ_REFERENCE.out.genome_gtf.map{ it[1] },
            PREPARE_RIBOSEQ_REFERENCE.out.genome_fai
        )


        }

    }

    if (!params.skip_psite && !params.skip_qc) {

        RUST_QC(
            PREPARE_RIBOSEQ_REFERENCE.out.transcript_info_fa,
            PREPARE_RIBOSEQ_REFERENCE.out.transcript_info,
            IDENTIFY_PSITES.out.psites.flatten()
        )
    }


    // PCA on gene-level RPF counts and transcript-level P-sites
    if (!params.skip_psite) {

        PCA(
            GET_GENE_LEVEL_COUNTS.out.merged_counts_table,
            IDENTIFY_PSITES.out.cds_coverage,
            IDENTIFY_PSITES.out.cds_window_coverage,
            PREPARE_RIBOSEQ_REFERENCE.out.transcript_info
        )

    } else {

        PCA(
            GET_GENE_LEVEL_COUNTS.out.merged_counts_table,
            Channel.empty(),
            Channel.empty(),
            PREPARE_RIBOSEQ_REFERENCE.out.transcript_info
            )
    }

    // Run MULTIQC
    // if ribocutter skipped, use empty channel in multiqc

    if (params.skip_ribocutter) {

        ch_ribocutter = Channel.empty()

    } else {

        ch_ribocutter = RUN_RIBOCUTTER.out.ribocutter_mqc
    }

    if (!params.skip_premap && !params.skip_qc) {

        ch_logs = FASTQC.out.html.join(FASTQC.out.zip)
            .map { [it[1], it[2]] }
            .collect()
            .mix(
                PREMAP.out.log.map { it[1] }.collect(),
                MAP.out.log.map { it[1] }.collect(),
                PCA.out.pca_mqc,
                SUMMARISE_RIBOSEQ_QC.out.mqc,
                ch_ribocutter
            )
            .collect()

    } else if (!params.skip_premap && params.skip_qc) {

        ch_logs = FASTQC.out.html.join(FASTQC.out.zip)
            .map { [it[1], it[2]] }
            .collect()
            .mix(
                PREMAP.out.log.map { it[1] }.collect(),
                MAP.out.log.map { it[1] }.collect(),
                PCA.out.pca_mqc,
                ch_ribocutter
            )
            .collect()

    } else if (params.skip_premap && params.skip_qc) {

        ch_logs = FASTQC.out.html.join(FASTQC.out.zip)
            .map { [it[1], it[2]] }
            .collect()
            .mix(
                MAP.out.log.map { it[1] }.collect(),
                PCA.out.pca_mqc,
                ch_ribocutter
            )
            .collect()

    } else {

        ch_logs = FASTQC.out.html.join(FASTQC.out.zip)
            .map { [it[1], it[2]] }
            .collect()
            .mix(
                MAP.out.log.map { it[1] }.collect(),
                PCA.out.pca_mqc,
                SUMMARISE_RIBOSEQ_QC.out.mqc,
                ch_ribocutter
            )
            .collect()
    }

    MULTIQC(ch_logs, ch_multiqc_config, ch_multiqc_group_config)

}


workflow {
    RIBOSEQ ()
}

/*
COMPLETION EVENTS
*/

workflow.onComplete {

    if (workflow.success) {
        log.info "-\033[0;34m[riboseq]\033[0;32m Pipeline completed successfully\033[0m-\n"
    } else {
        log.info "-\033[0;34m[riboseq]\033[1;91m Pipeline completed with errors\033[0m\n"
    }

}
